const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Behaviors.Tween,
		C3.Plugins.Particles,
		C3.Behaviors.Timer,
		C3.Plugins.Text,
		C3.Behaviors.Flash,
		C3.Behaviors.Fade,
		C3.Plugins.TiledBg,
		C3.Behaviors.Persist,
		C3.Plugins.sliderbar,
		C3.Plugins.Browser,
		C3.Plugins.Button,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.WaitForSignal,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.Signal,
		C3.Behaviors.Flash.Cnds.OnFlashEnded,
		C3.Plugins.Text.Acts.Destroy,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Touch.Cnds.OnNthTouchStart,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Cnds.HasNthTouch,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Exps.Height,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Acts.CreateObjectByName,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.TiledBg.Acts.MoveToTop,
		C3.Behaviors.Fade.Acts.SetFadeInTime,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.sliderbar.Acts.SetVisible,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.sliderbar.Cnds.OnChanging,
		C3.Plugins.Text.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.sliderbar.Exps.Value,
		C3.Plugins.Browser.Cnds.IsFullscreen,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.ToggleBoolVar
	];
};
self.C3_JsPropNameTable = [
	{VectorX: 0},
	{VectorY: 0},
	{RotationSpeed: 0},
	{ActAsBomb: 0},
	{Object: 0},
	{Touch: 0},
	{Tween: 0},
	{Blade: 0},
	{Luminosity: 0},
	{HalfObject: 0},
	{Timer: 0},
	{Juice_0: 0},
	{BladeSmoother: 0},
	{Fullscreen: 0},
	{install: 0},
	{InstructionsText: 0},
	{GameManager: 0},
	{NewY: 0},
	{Flash: 0},
	{ScoreText: 0},
	{Bomb1_0: 0},
	{Bomb2_0: 0},
	{SliceText: 0},
	{Door: 0},
	{Fade: 0},
	{strike_info: 0},
	{Background: 0},
	{strike_counter: 0},
	{Layout: 0},
	{NumberValue: 0},
	{Persist: 0},
	{LayoutPortal: 0},
	{GameMode: 0},
	{Browser: 0},
	{lowperf: 0},
	{Mode: 0},
	{GameOn: 0},
	{Strikeless: 0},
	{Strike: 0},
	{BOMBSPAWNRATE: 0},
	{NoFall: 0},
	{InvertBombs: 0},
	{FirstInteraction: 0},
	{DOUBLESPAWNRATE: 0},
	{SCREENHORIZONTALMARGIN: 0},
	{RotationDirection: 0},
	{AllowPlayerToCut: 0},
	{PreviousX: 0},
	{GPUBAD: 0},
	{PreviousY: 0},
	{RandomForce: 0},
	{Score: 0},
	{GameIsOver: 0},
	{Direction: 0},
	{CurrentValue: 0},
	{TargetValue: 0},
	{Speed: 0}
];

self.InstanceType = {
	Object: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Blade: class extends self.ISpriteInstance {},
	HalfObject: class extends self.ISpriteInstance {},
	Juice_0: class extends self.IParticlesInstance {},
	BladeSmoother: class extends self.ISpriteInstance {},
	InstructionsText: class extends self.ITextInstance {},
	GameManager: class extends self.ISpriteInstance {},
	ScoreText: class extends self.ITextInstance {},
	Bomb1_0: class extends self.IParticlesInstance {},
	Bomb2_0: class extends self.IParticlesInstance {},
	SliceText: class extends self.ITextInstance {},
	Door: class extends self.ISpriteInstance {},
	strike_info: class extends self.ITextInstance {},
	Background: class extends self.ITiledBackgroundInstance {},
	strike_counter: class extends self.ITextInstance {},
	LayoutPortal: class extends self.ITextInstance {},
	Fade: class extends self.ITiledBackgroundInstance {},
	GameMode: class extends self.ISliderBarInstance {},
	Browser: class extends self.IInstance {},
	lowperf: class extends self.IButtonInstance {}
}